class_icons = {'guardian': 'https://imgur.com/zexWTiU.png', 'hierophant': 'https://imgur.com/NS1jBV8.png',
               'inquisitor': 'https://imgur.com/sPaesID.png', 'juggernaut': 'https://imgur.com/whGGliW.png',
               'necromancer': 'https://imgur.com/qHc2mTH.png', 'ascendant': 'https://imgur.com/OhWnmHr.png',
               'pathfinder': 'https://imgur.com/l86Qh0I.png', 'occultist': 'https://imgur.com/eYoTFWl.png',
               'slayer': 'https://imgur.com/cC7g5BW.png', 'raider': 'https://imgur.com/7Qiv7jC.png',
               'deadeye': 'https://imgur.com/oiFSPmg.png', 'saboteur': 'https://imgur.com/UGgJJIu.png',
               'champion': 'https://imgur.com/cpZDveV.png', 'chieftain': 'https://imgur.com/mkcqU6j.png',
               'marauder': 'https://imgur.com/vG2dzpD.png', 'trickster': 'https://imgur.com/WsxFHeu.png',
               'duelist': 'https://imgur.com/DkMnsFh.png', 'scion': 'https://imgur.com/R3X8adS.png',
               'ranger': 'https://imgur.com/aT7ikyR.png', 'templar': 'https://imgur.com/WPDRLFL.png',
               'assassin': 'https://imgur.com/LteJ4J4.png', 'witch': 'https://imgur.com/HXm5BWA.png',
               'gladiator': 'https://imgur.com/VWWJPNZ.png', 'berserker': 'https://imgur.com/DIdtg6Q.png',
               'elementalist': 'https://imgur.com/hJXTaOe.png', 'shadow': 'https://imgur.com/PTmFjZY.png'}
