on: [push]
jobs:
  zana_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Build frontend image
        run: docker image build -t konggal/zana .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Inspect
        run: |
          docker image inspect zana
      - name: push
        run: docker push konggal/zana:latest